triggers:
- envs: []
  last_enabled_at: 2024-02-22 05:48:44.125487
  name: travel_trigger
  pipeline_uuid: travel_data
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-22 05:00:00
  status: inactive
  variables: {}
